### ISSUE TITLE
Cursor position resets to beginning when edit button of card is clicked

### ISSUE THREAD

**Issue by sajib21** [SelfDevTV/trello-clone#4]
I think when we click the edit button, the cursor should stay on the last position. I used <input> instead of <StyledTextarea> and <input> works normally. Will try to solve this myself.

**Comment by SelfDevTV** [comment]
Hiho, I'm so sorry that Ive been absent and you fixed an issue. I will have a look at this the next few days and will approve it. Very cool thx for doing that!
